services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      - PRIMARY=${PRIMARY}
      - REPLICAS=${REPLICAS}
      - FULL_SYNC=${FULL_SYNC}
      - CRON=${CRON}
      - RUN_GRAVITY=${RUN_GRAVITY}
      - TZ=${TZ}
      - CLIENT_SKIP_TLS_VERIFICATION=${CLIENT_SKIP_TLS_VERIFICATION}
    env_file: .env