services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    container_name: orbital-sync
    restart: unless-stopped
    environment:
      PRIMARY_HOST_BASE_URL: 'http://10.0.0.247'
      PRIMARY_HOST_PASSWORD: ${PRIMARY_HOST_PASSWORD}
      SECONDARY_HOSTS_1_BASE_URL: 'http://10.0.0.36'
      SECONDARY_HOSTS_1_PASSWORD: ${SECONDARY_HOSTS_1_PASSWORD}
      #SECONDARY_HOSTS_2_BASE_URL: 'http://192.168.1.3'
      #SECONDARY_HOSTS_2_PASSWORD: 'your_password3'
      #SECONDARY_HOSTS_3_BASE_URL: 'http://server:8080'
      #SECONDARY_HOSTS_3_PASSWORD: 'your_password4'
      #SECONDARY_HOSTS_3_PATH: '/apps/pi-hole'
      INTERVAL_MINUTES: 15
    env_file: .env