services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      FTLCONF_dns_listeningMode: all
    volumes:
      - 'opt/stacks/pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped