services:
  valheim-server:
    image: lloesche/valheim-server
    container_name: valheim
    cap_add:
      - sys_nice
    stop_grace_period: 120s
    ports:
      - 2456-2457:2456-2457/udp
    volumes:
      - /home/ben/docker/valheim/config:/config
      - /home/ben/docker/valheim/data:/opt/valheim
    environment:
      SERVER_NAME: ${SERVER_NAME}
      WORLD_NAME: ${WORLD_NAME}
      SERVER_PASS: ${SERVER_PASS}
      SERVER_PUBLIC: ${SERVER_PUBLIC}
      ENABLE_CROSSPLAY: ${ENABLE_CROSSPLAY}
      TZ: ${TZ}
      UPDATE_CRON: ${UPDATE_CRON}
      UPDATE_IF_IDLE: ${UPDATE_IF_IDLE}
      RESTART_CRON: ${RESTART_CRON}
      RESTART_IF_IDLE: ${RESTART_IF_IDLE}
      BACKUPS: ${BACKUPS}
      BACKUPS_CRON: ${BACKUPS_CRON}
      BACKUPS_MAX_AGE: ${BACKUPS_MAX_AGE}
      BACKUPS_MAX_COUNT: ${BACKUPS_MAX_COUNT}
      BACKUPS_IF_IDLE: ${BACKUPS_IF_IDLE}
      BACKUPS_IDLE_GRACE_PERIOD: ${BACKUPS_IDLE_GRACE_PERIOD}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped
networks: {}